[profile.default]
src = 'contracts'
libs = ['lib', '../../node_modules']
cache_path = 'foundry-cache'
out = 'foundry-out'
fs_permissions = [{ access = "read", path = "./"}]
ffi = true

[profile.lite]
optimizer = false

[profile.default.libraries]
NouncillorsDescriptor = { NFTDescriptor = "0xLibrary1Address" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
