[profile.default]
src = 'contracts'
libs = ['lib', '../../node_modules']
cache_path = 'foundry-cache'
out = 'foundry-out'
fs_permissions = [{ access = "read", path = "./"}]

[profile.lite]
optimizer = false

# [libraries]
# NouncillorsDescriptor.sol:NouncillorsDescriptor = "{NFTDescriptor address}"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
